name: ğŸ“¢ Publish Add-on

on:
  release:
    types: [published]

jobs:
  publish:
    name: ğŸ“¢ Publish Add-on
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Dispatch Repository Updater update signal
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: stuartparmenter/homeassistant-addons
          event-type: update
          client-payload: '{"addon": "rtl433"}'